### ISSUE TITLE
Race condition in testExceptionHandling

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ApplicationCore#103]
testShutdown in testExceptionHandling frequently fails because the error message of the exception is wrong (exception happens in write instead of read). This is a bug in the test. I could reproduce it quite reliably by running "stress --cpu 32 --io 16 --vm 8" in the background.

ApplicationCore propagates initial values. The TestFacility writes initially all writeable PVs on the control system side. These values get written to the device asynchronously after the device is open. If due to a race one of the writes gets delayed until after the ExceptionDummy has been configured to throw, we will run into this error.

It can be solved by setting non-zero default values to all PVs that are connected to the device (via TestFacility::setScalarDefault/setArrayDefault) and wait until these values are actually present on the device, before configuring the dummy to throw.

Alternativly one could not use TestFacility::runApplication() and run the application by hand. In this case, no default values are written. I think this will logically reduce the test coverage though. This still might be acceptable, since only the shutdown behaviour shall be tested here. I think we still properly test this, even in we run into this condition. So as a last solution, one could simply remove the checks for the exception message, since it is not essential for the test how the device has arrived in the error condition.

**Comment by killenb** [comment]
I think I would write the non-zero default values. This has the best test coverage an is the most realistic as all real CS adapters also write initial values.
