### ISSUE TITLE
Implement the StatusAggregator

### ISSUE THREAD

**Issue by ckampm** [ChimeraTK/ApplicationCore#107]
This is a follow-up from #14, the implementation has been started in there. See that ticket's description (and #13) for the concept and implementation hints.

Current status (commit cba9645):

The module and a related test are created. The StatusMonitor has been refactored so that it provides a non-templated base class that can be tested with dynamic_cast. We are still figuring out a feasible approach for detecting the instances to be aggregated. Currently, I do not have a working solution. For the TestApplication, the modules are detected correctly, but this crashes if the HierarchyModifiers are set to something else than `none`. See also comments in `StatusAggregator.cc`.

A vector of push-type inputs has been included as `statusInput`. Implementation of the actual aggregation and the prioritization of statuses has not been started yet.  

Definition of Complete:
- [ ] Implementation
- [ ] Tests, also with some real life scenarios
- [ ] Doxygen reference documentation
- [ ] Doxygen page documenting how to use it with an example
- [ ] Review by @mhier

**Comment by mhier** [comment]
Please try to avoid committing to ApplicationCore for now (at least for source code, spec doc files are ok of course). We need to fix the framework first... If you need to go ahead with implementation, talk to me first, please.

**Comment by mhier** [comment]
Problems are solved, you can go ahead with committing code.

**Comment by ckampm** [comment]
The statement above about  HierarchyModifiers are set to something else than `none` is not correct. I'm looking into this.

**Comment by ckampm** [comment]
The problem about HierarchyModifiers other than `none` resolved.

Note on requirements and implementation hints given in the preceding tickets: These have changed. The spec can be found [here](https://chimeratk.github.io/ApplicationCore/master/spec__status_aggregator.html). 

The current implementation virtualizes the entire Application and navigates to the location of the StatusAggregator in the virtual hierarchy. Detection of underlying instances is still not complete. See comments in `StatusAggregator::populateStatusInput` on possible approaches. The code currently foresees scanning for instances level-per-level, but properly obtaining a list of modules per level is not finished. Ideally, the API offered a function to retrieve a list of  actual (C++) modules for a given `VirtualModule`.

Handling of the Module types in `scanAndPopulateFromHierarchyLevel` should be reviewed against the spec, connection to the status inputs is missing, and prioritization of status values has to be implemented

**Comment by mhier** [comment]
This ticket is now being tracked in Redmine #7982, but due to the amount of information here we keep this ticket open and refer to it from Redmine.

**Comment by mhier** [comment]
done
