### ISSUE TITLE
TriggerFanOut must write outputs with data invalid flag when handling an exception

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#110]
As the TriggerFanOut is using a transfer group under the hood, it has to do the exception handling here as well (and cannot use the functionality of the ExceptionHandlingDecorator at the moment).
The code is very similar though, but details are slightly different.
At the place where the ExceptionHandlingDecorator is calling its "setOwnerValidity" internal function, the TriggerFanOut has to increment its "exceptionFaultCounter" (such that TriggerFanOut::getDataValidity() returns false and the MetaDataPropagatingDecorator can pick it up), and then write all the outputs. 
While recovering (i.e. after read has been retried successfully), the exceptionFaultCounter must be decremented. The outputs will be written in any case, so you don't have to do this again.

(Note for understanding: The TriggerFanOut always has inputs only from one device.)

* [ ] When implemented, activate `testReadDeviceWithTrigger` in `testPropagateDataFaultFlag.cc`

**Comment by killenb** [comment]
s affected by the interface change in #99 (only small changes)

**Comment by mhier** [comment]
Attention: the outcome of #120 affects this ticket. Please check the status of #120 and talk to the assignee...

**Comment by killenb** [comment]
With the new exception handling specification (result of #86) this ticket is obsolete and invalid.
