### ISSUE TITLE
Generic modules for status monitoring - Part 2

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ApplicationCore#14]
This ticket depends on #13 - read that ticket first for background information.

**Implement a StatusAggregator module**
- Collect the results of a number of StatusMonitor instances and aggregates them into a single status with the same value scheme
- Also other StatusAggregator instances can be connected to this instance so its status gets aggregated into the single status. This allows to build arbitrary hierarchies of aggregators
- The StatusMonitor and StatusAggregator instances to be connected into the StatusAggregator should be found automatically as follows:
  - A StatusAggregator aggregates all instances in the hierarchy of ApplicationCore Modules which are at the same hierarchy level or below
  - Two StatusAggregator instances cannot be on the same hierarchy level - this should throw a logic_error
  - If a StatusAggregator is found at some hierarchy level below, the search is stopped for that branch of the hierarchy tree, i.e. all variables which are already aggregated by that aggregator are not aggregated againn
- The StatusAggregator is configurable (by a constructor parameter, not a PV) in the way how the statuses are prioritised. The status with the highest priority within the aggregated instances defines the aggregated status. The following options exist (highest priority first):
  - error - warning - off - ok
  - error - warning - ok - off
  - error - warning - ok or off - mixed state of ok and off results in warning
  - off - error - warning - ok

Hints for implementation:
- Collection of instances to be aggregated has to be done in the constructor, later, e.g. in `prepare()` is too late, because the variable household is then fixed and inputs from the aggregated monitors can not be added anymore. 
- Search for instances must be done on the virtual hierarchy, use getOwner()->findTag(".*"), then use getSubmoduleList(), getAccessorList on the VirtualModule (see also comment below)
- a dynamic_cast finds out, whether a submodule is a StatusMonitor, StatusAggregator, a ModuleGroup or something else
- If it's a ModuleGroup, recurse into it via EntityOwner::getSubmoduleList(), unless a StatusAggregator exists on the same level
- "Something else" can only be an other ApplicationModule, which we will ignore.

Hints for design/interface/usage:
- Allow specifying tags for the output status PV through the constructor

Definition of Complete:
- [ ] Implementation
- [ ] Tests, also with some real life scenarios
- [ ] Doxygen reference documentation
- [ ] Doxygen page documenting how to use it with an example
- [ ] Review by @mhier

**Comment by ckampm** [comment]
Further implementation to be done in #107.
