### ISSUE TITLE
implement correct return value of writeWithoutErrorBlocking

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#148]
I don't know if it is implementable, but writeWithoutErrorBlocking should return true (dataLost) if the content of the recovery accessor is replaces, but the previous value has not been written yet.
Usually the return value is false because the recovery accessor will take care that the data eventually is written, so it is not lost.

**Comment by mhier** [comment]
should now always be the case for all writes, since they should never block in case of an error.

**Comment by killenb** [comment]
writeWithoutErrorBlocking does not exist any more in the current scheme
