### ISSUE TITLE
Writing uint8 to the persist file fails

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ApplicationCore#154]
Just because I'm still missing bool type in CTK and I did not want to use uint for a bool type variable I used uint8.

In my application and the control system everything is fine. But when I close my application and start it again the persist file can not be opened and a new one is created. 

The line that corresponds to the uint8 value looks like this in the persist file after closing the application:
```
  <variable name="/test/dummy" type="uint8">
    <val i="0" v="^A"/>
  </variable>
```

**Comment by mhier** [comment]
This looks like the classic problem that C(++) doesn't distinguish between char and (u)int8... Should be an easy fix: just convert the value into a normal int, if (and only if) it is a (u)int8, before writing it to file.

**Comment by zenker** [comment]
As I tried to point out I tried to use it as a bool type variable in my application. After seeing that problem I now use uint again. 

My point is that, the persist file writer/reader should be able to handle uint8, right?
Currently it fails and produces corrupt persist files.

**Comment by mhier** [comment]
> My point is that, the persist file writer/reader should be able to handle uint8, right?

Sure, it should handle all types defined in DeviceAccess' SupportedUserTypes.h

> Currently it fails and produces corrupt persist files.

That's clearly a bug.

**Comment by mhier** [comment]
This ticket belongs to the ControlSystemAdapter. I have created a replacement ticket there.
