### ISSUE TITLE
Check tests for initial value propagation

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#156]
Child of #123 

The initial value propagation is connected with the exception handling scheme because the ExceptionHandlingDecorator takes care that no read transfer succeeds until the initial value could be received.

* [ ] Extend the tests to check that no value with invalid time stamp is propagated.
* [ ] ReadNonBlocking() and ReadLatest() must block until the initial value could be received
* [ ] Special scenario works: Only reading fails (simulate with exception dummy)
  * The device can be opened
  * The initialisation sequence runs through (may be empty)
  * Recovery accessors can be written -> The device is opened successfully and reports no error.
  * The first read operation is executed and fails during its transfer. The device goes to error state, but recovers immediately....
  * All reads block until the read exception has been turned off. The first value is valid and has the right content.

* [ ] All the tests should also work for transfer groups. They are only used in the TriggerFanOut. In the current implementation this is not working cleanly yet. Come up with a test scenario and comment it out. Note in the implementation ticket (FIXME does not exist yet) that the test should be activated.

**Comment by killenb** [comment]
This ticket seem a bit outdated since we have the systematic tests in #179. I see it as an addition to review #179 and check that all special cases mentioned here are covered.

**Comment by mhier** [comment]
Closed in favour of #179
