### ISSUE TITLE
ExceptionHandlingDecorator: for readAsync preRead() must block until the transfer is allowed

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#157]
In doReadTransferAsync a valid TransferFuture with a continuation to the accessor's postRead must be returned. This future is coming from the backend. It would at be very difficult to come up with a mechanism to return a future that also does the job of the ExceptionHandlingDecorator and registers the Transfer with the DeviceModule and only starts a new one if the DeviceModule allows. Especially, DeviceModule is an ApplicationCore concept, and Backends are pure DeviceAccess and know nothing about it.

Solution: If TransferType is readAsync then ExceptionHandlingDecorator::preRead() must block until DeviceModule::startTransfer returns true. Then the future from the backend is always allowed to try the transfer.

This ticket has to be done after  #138, Phase 2.

**Comment by mhier** [comment]
no longer valid
