### ISSUE TITLE
Write test for  "The user can decide to flag individual outputs"

### ISSUE THREAD

**Issue by toseko** [ChimeraTK/ApplicationCore#167]
h2. Background info

According to spec:
https://chimeratk.github.io/ApplicationCore/master/spec_data_validity_propagation.html

1.1.6 The user can decide to flag individual outputs as bad. However, the user cannot actively set an output to 'ok' if the data validity of the module is 'faulty' (to be more precise: if the validity of the corresponding DataFaultCounter is faulty).

The feature has been implemented in branch:
wip/tkozak-change-setDataValidity-4-NDRegisterAccessorDecorator
and merge with the master, but tests are missing.

h2. Implementation

Implement tests which will test whether flag behaves correctly in all possible combination:
1) Signal OK and parrent module OK -> should give OK
2) Signal OK and parrent module NOT OK -> should give NOT OK for a signal
3) Signal NOT OK and parrent module OK -> should give NOT OK  for a signal
4) Signal NOT OK and parrent module NOT OK -> should give NOT OK  for a signal

h2. Definition of done

* [x] Work-in-progress branch is merged into the master (use --no-ff). Don’t delete the branch yet.
* [ ] Tests are in place (with reference in the spec)

**Comment by killenb** [comment]
The implementation is in place since some time. But the tests are still missing.

**Comment by mhier** [comment]
closed in favour of redmine #8369
