### ISSUE TITLE
example is completely broken

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#177]
The implementation of the TimerDummyDevice is broken.

- It needs an implementation without wait_for_new_data for the accessor
- It needs to implement setException() and activateAsyncRead() properly
- Data must be send through the _readQueue

Even with a proper implementation the example will not run until #176 is fixed.

To get the demo server running one could use the PeriodicTrigger, but I think having an example how to properly implement a push-type DeviceBackend is the more valuable part of this example.

**Comment by mhier** [comment]
The TimerDummyDevice can be replaced by an ExceptionDummy now, since it supports wait_for_new_data.

**Comment by killenb** [comment]
Ah, I did not think about that. Is it thread-safe? For the purpose of a test this definitely would be sufficient.
We also have the periodic trigger now, which did not exist when the example was written. Although I have to admit it makes a small difference if you instantiate a device or a trigger in the app. The one with the trigger cannot run with real timing from a real device.

I see the didactic value of this TimerDummy in the demonstration how to write a backend push-type support from scratch (incl. setException(), activateAsyncRead() etc). It probably should go to DeviceAccess then, but there the use case in the test ist always so limited. It is much nicer to see how it works in ApplicationCore.

**Comment by mhier** [comment]
Thread-safe in which way?

A demonstration how to write backends should be placed in DeviceAccess, not in ApplicationCore. It was never the intention do show how to write a backend, the TimerDummy was never implemented properly.

**Comment by killenb** [comment]
Postponed because it only affects an example.

**Comment by mhier** [comment]
Closed in favour of redmine #8371
