### ISSUE TITLE
testExceptionHandling is failing

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#184]
runtimeErrorHandling_testMultipleWrites in testExceptionHandling is failing.

**Comment by vargheseg** [comment]
These are some of the pending tests:
- (Section B 2.3.2 of spec) Test write from multiple process variables to confirm the order they get written in on recovery.
- (B 2.3.5) Write takes place before the device is considered fully recovered again and other transfers are allowed
- (B 3) Tests for Recovery procedure

**Comment by killenb** [comment]
solved in de80fe0
