### ISSUE TITLE
Connecting  device module to control system module

### ISSUE THREAD

**Issue by nshehz** [ChimeraTK/ApplicationCore#21]
Connecting a device module to a control system module e.g.,
`dev(RegisterName, ctk::UpdateMode::push) >> csModule[configLocation](RegisterName);`
fails with an exeception

> terminate called after throwing an instance of 'ChimeraTK::logic_error'
> what():  The feeding node has zero (or undefined) length!
> 
Reason is that the VariableNetworkNode operator() in DeviceModule sets the nElements = 0 by default.

**Comment by mhier** [comment]
either explicitly set number of elements, or preferably use dev.connectTo(cs) or even the ConnectingDeviceModule instead.
