### ISSUE TITLE
Exception handling - part 3

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ApplicationCore#25]
This is a child task of #10 and follows up on task #12. Can be done in parallel with #26.

Current situation:
runtime_error exceptions coming from devices are now caught and made visible to the control system. ApplicationModules which read those variables will be blocked until the exception state is resolved. TriggerFanOuts read multiple poll-type device variables when a trigger arrives. Those variables might come from different devices. If one of the devices fails, currently the entire TriggerFanOuts will block until the device is recovered.

Task:
Change the connection making code (in class Application) so it creates a separate TriggerFanOut for each device. This makes not only sure that faulty devices will not block readout of other devices, but also will parallelise the readout of multiple devices, which is a performance improvement (completely disconnected from exception handling).

DoD:
- [x] Implementation
- [x] Add test with two ExceptionDummy instances (see test for exception handling) to make sure that readout of on device continues while the other is in an exception state.

**Comment by jhktimm** [comment]
To make separate TriggerFanOuts for each device, don't I have to create separate feeders (feeding node) for each device first?

**Comment by mhier** [comment]
Each TriggerFanOut deals with several variable networks at the same time, which are triggered by the same trigger. Each variable network has its own feeder and one or more consumers. You do not need to change anything about the variable networks.

On the other hand, the trigger itself is a variable network, too. The TriggerFanOut has a consumer of this trigger network. This is the accessor on which the blocking read() is called in the loop. You will need to create additional consumers in the trigger network, one for each TriggerFanOut.

**Comment by mhier** [comment]
issue resolved with the merge
