### ISSUE TITLE
Allow unallowed hierarchy building on purpose

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ApplicationCore#34]
Could this be converted to something like a warning:
https://github.com/ChimeraTK/ApplicationCore/blob/67b8eb5f477404a3aaa52cab603fa157fa7c97b2/src/ControlSystemModule.cc#L28

Currently the https://github.com/ChimeraTK/ServerMockup is not working anymore because of this assertion. I just tested what happens when removing this assertion. The ServerMockup runs fine again and all the ApplicationCore test succeed. 

It would be very inconvenient (if possible at all) to reproduce the variable tree using ModuleGroups and VariableGroups.

**Comment by mhier** [comment]
I think you should rather fix the ServerMockup. Allowing this has bad side effects and might create issues which are very hard to debug.

It is perfectly possible to put your variables in VariableGroups forming the required hierarchy, it has been done a couple of times. Please have a look e.g. at the ConfigReader or the MicroDAQ modules.
