### ISSUE TITLE
Produce proper error message when destroying a module which already has connected variables

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ApplicationCore#5]
Typical example: Module depending on configuration parameters is initialised only in the constructor body of the application. By mistake a connection to that module is made before the module is replaced with the final (properly configured) instance. In the replacement (assignment operation) the destructor of the previous instance is called, which should throw if connections to variables inside the module have already been made. Only during the shutdown phase of the application modules may be destroyed which have connections.

Also default constructed modules should not allow making any connection in the first place.

**Comment by mhier** [comment]
Now tracked by redmine #8357

**Comment by phako** [comment]
https://github.com/ChimeraTK/ApplicationCore/pull/377
