### ISSUE TITLE
VariableGroup::readAll() fails to update all push-type variables

### ISSUE THREAD

**Issue by phako** [ChimeraTK/ApplicationCore#50]
In the code below, somehow the ch7 (possibly others, but the data is usually constant) was not updated properly after the readAll().

The values are connected to the module it lives in using the trigger from the PeriodicTrigger

```
    struct : ctk::VariableGroup {
      using ctk::VariableGroup::VariableGroup;

      ctk::ScalarPushInput<int16_t> ch1{this, "CAR_ADC_CH1", "", ""};
      ctk::ScalarPushInput<int16_t> ch2{this, "CAR_ADC_CH2", "", ""};
      ctk::ScalarPushInput<int16_t> ch3{this, "CAR_ADC_CH3", "", ""};
      ctk::ScalarPushInput<int16_t> ch4{this, "CAR_ADC_CH4", "", ""};
      ctk::ScalarPushInput<int16_t> ch5{this, "CAR_ADC_CH5", "", ""};
      ctk::ScalarPushInput<int16_t> ch6{this, "CAR_ADC_CH6", "", ""};
      ctk::ScalarPushInput<int16_t> ch7{this, "CAR_ADC_CH7", "", ""};
      ctk::ScalarPushInput<int16_t> ch8{this, "CAR_ADC_CH8", "", ""};
      ctk::ScalarPushInput<int16_t> ch9{this, "CAR_ADC_CH9", "", ""};
      // 10, 11, 12 handled elsewhere
      ctk::ScalarPushInput<int16_t> ch12{this, "CAR_ADC_CH12", "", ""};
      ctk::ScalarPushInput<int16_t> ch13{this, "CAR_ADC_CH13", "", ""};
      ctk::ScalarPushInput<int16_t> ch14{this, "CAR_ADC_CH14", "", ""};
      ctk::ScalarPushInput<int16_t> ch15{this, "CAR_ADC_CH15", "", ""};
    } input{this, "DeviceIn", "ADC input channels", ctk::HierarchyModifier::hideThis, {"ULOG_IN"}};
  ...
  void mainLoop() {
    input.readAll();
    ...
  }
```

**Comment by mhier** [comment]
Can you provide a self-contained minimal example to reproduce this issue? readAll() itself is so simple that it could hardly such a bug. The problem must be somewhere else...

**Comment by killenb** [comment]
I think this could indicate a crucial, hidden bug, even in the locigal name mapping. Are the data de-multiplexed 2D arrays?
Before we can address this we have to be able to consistently reproduce this (at least with a significant probability like at least 1 out of 100 or so if it's a race condition).

**Comment by phako** [comment]
No the data is coming from the ulog backend; perhaps there was a bug in there

**Comment by mhier** [comment]
Is this still reproducible? Otherwise I would close it.

**Comment by phako** [comment]
I will check when fixing the backend of the uLog server and reopen if it still is the case.
