### ISSUE TITLE
Fix fluctuating error state

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#54]
The device status is always reported as OK after 500 ms.

The recovery mechanism for failed devices is to call open() again and wait until the Device reports isFunctional() again. Some devices (network based without permanent connection) don't take any recovery action during open() and always report isFunctional(). Currently all devices do this. This leads to the unwanted behaviour that the device state is always reported as OK after 500 ms (if the device does not have an initialisation procedure which itself throws again).

Correct behaviour:
* The device reports _error_ until a successful read or write could be performed. 

This behaviour works well with connection-less backends with unstable network, where sometimes network interruptions occur and just go away, as well as with backends which actively have to resolve the error. The latter happens in the DeviceModule thread, which wakes up the failing accessors to retry.

Implementation:

Details are not fully worked out. The DeviceModule thread needs to get notified that the error  condition has been resolved. So it after being woken up there can be two actions: send error or resolve error. Do we have two different sleeping points? But what to do with additional errors that come in? Or just one sleeping point? Do we need an extra queue or extend the meaning of the predicate for the condition variable?

When #56 is already implemented, make sure that readNonBlocking and readLatest have the correct behaviour:
* They return immediately with data invalid. The DeviceModule thread is allowed to reset the device error flag. However, it will only do this after the next read/write (of another or the same) accessor is successful.

**Comment by phako** [comment]
Also this becomes quite spammy:
```
WARNING: Data loss in scalar property CTRL.M34.A26.L3/Devices.ULOG.status due to failed data matching between value and macro pulse number.
WARNING: Data loss in scalar property CTRL.M34.A26.L3/Devices.ULOG.message due to failed data matching between value and macro pulse number.
```

**Comment by mhier** [comment]
@phako that might be a configuration error in your doocs mapping. Don't attach the macro pulse number to the Device error status (or any other data not related to the mpn).

**Comment by phako** [comment]
I merely followed the example and put macro_pulse_number_source on top of the DOOCS config. That example is probably misleading then

**Comment by killenb** [comment]
The symptom of a fluctuating error state is only a side effect of the backends not implementing ifFunctional() correctly. The bug is that the default implementation is always wrong in these cases. 
This has to be solved in DeviceAccess and the Backends. I therefore close this ticket.
