### ISSUE TITLE
Review the shutdown test in testExceptionHandling

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#55]
The shutdown test is supposed to cover all scenarios where an accessor could block, and check that the application destructor can join all threads and shutdown without blocking.
However, DeviceAccessors can be placed directly into all kinds of objects by the connection code: The control system module, user modules, ConcuminFanOuts, FeedingFanOuts, ThreadedFanOuts, TriggerFanOuts. Please review the test if there are other classes which are not covered, and if all of the above are handled by the test. (The TriggerFanOut is not, but the mechanism is not in place in Device for tests, and probably this will not throw but just not send in case of error).

**Comment by mhier** [comment]
Now on redmine #8364
