### ISSUE TITLE
Update Docu: Device exception handling

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#58]
* Update the exception handling doxygen page. The description should be detailed enough to server as specification for the implementation. Do not describe implementation  details like the conditons variables or the exception  reporting queue, but the behaviour as seen from the Device and the application programmer.

### Exception handling

* Document the exact behaviour of handling and reporting of `runtime_error` thrown by Device and its accessors.
** A central thread is waiting for exceptions to be reported by all accessors of the device.
** If an exception is received it is reported and the device status goes to 1
** The thread tries in a loop to call Device::open(), which is supposed to recover the device, until the device reports isFunctional() again.
** After this the initialisaton seqeuence is run. If it fails this itself reports an exception and the recovery restarts.
** The accessor tries to execute the failed action (read/write) again. If it succeeds the device status reported to the CS is set to OK and the error message from the exception is cleared.

* Describe the seen behaviour in case of Devices which
** do not (or cannot) report error states (`isFunctional()` is always true) and one has to retry the read/write to see if the device is working again
** implement a recovery procedure and can report `isFunctional()` as false while the device is known to be not operational.
* Describe when the initialisation will be executed
* Describe the difference of the blocking read() in contrast to readNonBlocking() and readLatest()

**Comment by mhier** [comment]
This has been written up in the specification. User documentation is missing though, a new ticket for this will be created on redmine.
