### ISSUE TITLE
Review the exception handling and invalid data reporting scheme

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#61]
### Reading

Currently there is a conceptual issue with the invalid flag propagation:

* read() is blocking until the error is resolved. Hence the modules, incl. the control system module, never see invalid data. The server is just stuck.

Proposed solution:
* read() shall not block but return with invalid data. This causes all modules to run at least once with invalid data to report that the calculated values are stale.
* The ProcessArray shall propagate invalid data only once.
  * If the data is invalid, it shall remember this and not send out data invalid data any more (already implemented like this in the ThreadFanOut).
  *  In addition, it shall not overwrite its output buffer, so the last value can still be displayed and the algorithms run with the last known value + invalid flag, and not some random data that was received in a broken transmission.

Like this, application also de facto stops, but not because it blocks somewhere in the algorithm, but because no new data is coming in.

(What does not work but could be desirable: One value is updating, a second value from another device is broken, but the last known value is still "good enough" to give the expert an idea what is going on when calculating an output from the two inputs. This changing value would not be propagated any more).

### Writing

* Writing would still block to guarantee the order of send data. I don't know if in a general case this is a useful concept with a dysfunctional device. In case of unreliable network transmission but the device itself staying intact it is necessary. For other cases it might unnecessarily block. In any case it can prevent propagation of the invalid flag to the control system, so the server gets stuck without reporting any issue.

**Comment by mhier** [comment]
**Reading**

I don't think this is a good idea to implement this in this exact way. If read() returns when the underlying device sees an error, the corresponding module will be triggered in the same way as if new data had received. This might have unwanted side effects. Of course the application module could check whether an error has been received and react differently, but this defeats the purpose of the automated exception handling in ApplicationCore - this is exactly the burden we want to take away from the application modules.

Instead, the propagation of the error state has to happen inside read(). The ExceptionHandlingDecorator needs to take care of this before the call to DeviceModule::reportException(). It can do so by obtaining the owning module, asking it for all output accessors and writing the faulty data flag to them.

As a consequence, reading will still block from the application module's point of view, but the flag will be propagated as expected.

**Writing**

Maybe there is an argument that a failure in write() should also raise the error state for all module outputs. If write() blocks until the error is cleared, the other outputs are also not updated. Hence one could argue their values are outdated and thus the error state should be set. I am not really sure, we should think this through first.

For cases where blocking is unwanted, we probably should introduce something like Scalar/ArrayNonBlockingOutput, which will enforce the use of a ThreadedFanOut. Writes are then guaranteed to never block, even in case of long network timeouts. I would do this only when we find an application to use this (but maybe we should create the ticket for it for later reference).

**Comment by mhier** [comment]
This ticket has been superseded.
