### ISSUE TITLE
Add a template server as an example

### ISSUE THREAD

**Issue by ckampm** [ChimeraTK/ApplicationCore#64]
Add an example that provides a template for new ApplicationCore-based servers.

This issue was split from #23 as a dependency, so we first create a generic template and define the more specific (e.g. it must select a triggering scheme) standard server. This example should fulfill the same requirements regarding structure and the CMakeLists.txt that are mentioned in #23.

- [ ] Implementation
- [ ] Inline code documentation so beginners understand what's going on
- [x] Test based on ApplicationCore testable mode and a dummy device
- [x] Example configuration files with a dummy device, a logical name mapping layer and DOOCS config files (if the DOOCS adapter is found)
- [ ] User documentation doxygen page how to use it as a simple server
- [x] Setup Jenkins job

**Comment by ckampm** [comment]
The implementation should also include largely respect the points listed in #125. Create follow-up tickets for publishing version numbers.

**Comment by mhier** [comment]
not sure why this is still open... #125 should be the follow up ticket for this.
