### ISSUE TITLE
HierarchyModifier hideThis does not work if the name already exists

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#68]
If the "directory" that is supposed to be hidden for that class already existst, the hiding does not work.
If however the hidden directory does not exist yet, the hiding works.
I created an example that shows this: tests/executables_src/testHideThis.cc
There is a workaround: Use a name that does not exists for the hidden hierarchy.

Short version
```C++
// works, creates /A/in and /B/in
struct A : public VariableGroup{
  struct : public VariableGroup{
    ScalarPushInput<int> in{this, "in","",""}
  } self {this, "A",""}

  struct : public VariableGroup{
    ScalarOutput<int> in{this, "in","",""}
  } b {this, "B",""}
} a{this, "A","", HierarchyModifier::hideThis};

// does not work, creates /B/B/in 
struct : public VariableGroup{
  struct : public VariableGroup{
    ScalarPushInput<int> in{this, "in","",""}
  } self {this, "B",""}
} b{this, "B","", HierarchyModifier::hideThis};

// Workaround: name for hidden hierarchy must not exist.
// Cabling of a.b.in  to b2.self.in works (name in CS is /B/in)
struct : public VariableGroup{
  struct : public VariableGroup{
    ScalarPushInput<int> in{this, "in","","}
  } self {this, "B",""}
} b2{this, "B2","", HierarchyModifier::hideThis};

```

**Comment by mhier** [comment]
Why was this ticket closed? I think the problem is still there and it also exists with moveToRoot.

**Comment by mhier** [comment]
Forget my previous comment. I was misled by some confusing output of dump(). Still I don't really understand why this ticket is closed???

**Comment by killenb** [comment]
The ticket was closed because I fixed it. There is a test I wrote to reproduce the problem (testHideThis), and this shows that  it is working now.
This ticket only could affect hierarchy modifiers which hide the current level. moveToRoot does not do this. It must be something else.

**Comment by killenb** [comment]
I stumbled across the suspicious line when implementing oneLevelUp, fixed it and noticed that it solves this ticket.

**Comment by killenb** [comment]
btw: Do we need moveToRootAndHide? One cannot move accessors to root, only module groups, modules and variable groups.

**Comment by mhier** [comment]
All right. Sorry for the false alarm, I thought I saw a similar problem, but it appears I just couldn't read :-)

I don't know if we need moveToRootAndHide. For now, I would only implement it if we have an application which needs it. It would intrinsically allow moving variables to the root, which is not per-se forbidden or impossible. You probably can have this already now with hideThis.

**Comment by killenb** [comment]
about moveToRootAndHide
> You probably can have this already now with hideThis.
Yes, and with oneUpAndHide, which I need for the status monitor (there also will be oneLevelUp without hiding)

**Comment by mhier** [comment]
Since we are only beginning to explore the new world of hierarchy modifications, I would rather not introduce features which we have no use case for yet. Maybe we soon find a much better way to deal with these kind of problems, and than we nave a huge zoo of deprecated features we need to carry around for a long time, because nobody knows some are not actually used anywhere...
