### ISSUE TITLE
Logging module: don't use pointers to process variables

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ApplicationCore#7]
Something like this is not necessary to write:
`std::unique_ptr<ctk::ScalarOutput<std::string> > message;`

Instead of initialising the pointer in the constructor, use a default constructed ScalarOutput and use message.setMetadata() to set its name etc.

**Comment by zenker** [comment]
I need to assign an owner for the ScalarOutput variable, that is only known in the constructor. As far as I know I can not change the owner after creation.

**Comment by phako** [comment]
You can also use initializer list syntax in the constructor for initializing the members, i.e.

struct Foo {
int bar;
Foo(int baz) : bar{baz} {} 
};

**Comment by zenker** [comment]
Done...
