### ISSUE TITLE
Implement a StatusMonitor with windows around a nominal value

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#75]
The RangeMonitor with 4 independent threshold is very flexible. In practice, these thresholds are usually calculated as windows around a nominal value. As this is a typical scenario we should have a StatusMonitor for it.

Design proposal:
* Class WindowMonitor
* Imputs: nominalValue, warningDelta, errorDelta
* behaviour like RangeMonitor with 
   * lowerWarningThreshold = nominalValue - warningDelta
   * upperWarningThreshold = nominalValue + warningDelta
   * lowerErrorThreshold = nominalValue - errorDelta
   * upperErrorThreshold = nominalValue + errorDelta

Definition of done:
* [ ]  Implementation
* [ ] Doxygen documentation
* [ ] Unit test

**Comment by mhier** [comment]
done already,.
