### ISSUE TITLE
How to influence the direction of connections between the controlsystem and a device module

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ApplicationCore#77]
I just tried to connect a DeviceModule (OPC-UA backend) to the control system module doing something like:
`dev.connectTo(cs, trigger.tick)`

I ended up having all process variables connected as pushing from the control system to the device. This happened although I passed the trigger. The reason is that all variables from OPC-UA have read/write access. By setting them to read only in the backend the connections ended up as I intended: all device variables are pushed to the control system using the given trigger.

Now the question is, do I have to add an option to the OPC-UA backend that allows to mark variables read only just to achieve the intended behaviour when connecting the device module to the controlsytem module?
Or is it just a bug in ApplicationCore, because if I pass a trigger I imply that I want to receive updates in the control system. 
I tested with ApplicationCore version 01.09.03

**Comment by mhier** [comment]
You can use the logical name mapping backend to do this. It will also allow to map the name of the register to match the structure and naming convention of the application. To change the direction you can use the forceReadOnly plugin (and you can do even more stuff like applying simple math).

**Comment by zenker** [comment]
I'm using already the math plugin. How to change the direction using the math plugin or do I need to combine both plugins?

**Comment by mhier** [comment]
Simply combine both....

**Comment by zenker** [comment]
Ok that works.
