### ISSUE TITLE
MicroDaq module should use uint64_t trigger

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ApplicationCore#8]
Currently it is not possible to connect the PeriodicTrigger output tick to the MicroDAQ module. This is because MicroDAQ is expecting an int and PeriodicTrigger delivers uint_64

**Comment by mhier** [comment]
I think the only solution is to implement variable conversion in ApplicationCore. The MicroDaq is currently used e.g. in the llrfctrl server and there triggered through the macro pulse number, which is a int.

**Comment by zenker** [comment]
Hm. A conversion module is also what I'm using in my application. Another option would be to have several inputs to MicroDaq (int, uint64_t) and wait for any of them, but I'm not sure if unconnected inputs are allowed in ApplicationCore...

**Comment by mhier** [comment]
Multiple inputs would be obsolete once ApplicationCore supports automatic conversion... Actually the type of the trigger input should be void once void is supported by ChimeraTK.

**Comment by mhier** [comment]
long ago fixed by allowing arbitrary types via C++ template...
