### ISSUE TITLE
Fix data validity flag in ExceptionHandlingDecorator

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#80]
The ExceptionHandlingDecorator for device modules does not handle the data validity flag correctly.

It currently sets the validity flag of the target accessors, which is wrong. Instead, it has to set the validity flag of the owner.

Details:
* The decorator needs to be extended so it knows the owner
* In the genericTransfer there are two places where setDataValidity is set to faulty. Here the data validity of the owner has to be set to faulty instead.
* In the genericTransfer the data validity is set to ok after the callable succeeded. Instead, the validity of the owner has to be set to the validity of the target accessor (not to OK, the target might have valid or invalid data)

**Comment by mhier** [comment]
Note: normally the `MetaDataPropagatingRegisterDecorator` takes care of the propagation of the validity flag to the module. Only when the error handling loop is entered a similar action as in `MetaDataPropagatingRegisterDecorator<T>::doPostRead()` is required.

**Comment by killenb** [comment]
Also remove `ExceptionHandlingDecorator::validity`. Already in the previous implementation it was only accessed when it was `DataValidity::ok` , and effectively the delegated validity was processed.  With this, the overloading of `dataValidity()` and `setDataValidity()` can be removed (as the `ExceptionHandlingDecorator` is derrived from `NDRegisterAccessorDecorator`, which already implements all direct delegations).

**Comment by killenb** [comment]
There is a ticket for it (#57 ) which modifies the same code lines. Be careful when merging.

**Comment by toseko** [comment]
After deeper analysis we would out that dataValidity() must be keep because it should take into account local and remote validity flag value, but setDataValidity() must be removed, because it must not modify local data validity flag, not to brake scheme that owner incrementDataFaultCounter/decrementDataFaultCounter must be called in pairs(one increment for one decrement). Local validity flag is used to ensure this behavior

**Comment by toseko** [comment]
Tasks:
1) "The decorator needs to be extended so it knows the owner" =>
Decorator **may** have an owner. The owner is set with method: `void setOwner(EntityOwner* owner)`

2) "In the genericTransfer there are two places where setDataValidity is set to faulty. Here the data validity of the owner has to be set to faulty instead." =>
If owner is known/set, its validity will be altered with `incrementDataFaultCounter()` or `decrementDataFaultCounter()` called on the owner  (as done in `ExceptionHandlingDecorator  `) . Local validity of `ExceptionHandlingDecorator` is also set during exception handling.  Setting local and owner validity is done only for read operations.

3) "In the genericTransfer the data validity is set to ok after the callable succeeded. Instead, the validity of the owner has to be set to the validity of the target accessor (not to OK, the target might have valid or invalid data)" =>
Local validity and owner validity (if know/set) are set to validity of target accessor when call successful. It means that validity of target accessor is propageted to the owner (if set) in case of successfull call of read operation.
