### ISSUE TITLE
Remove genericTransfer decoration from pre/post read/write

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#82]
The genericTransfer function implements the error handling functionality, and is called within all decorated functions. However, read() and write() consist of three steps:

* doPreRead() / doPreWrite() which prepare the buffer for transfer from the user buffer
* the actual transfer (access to the "hardware")
* doPostRead()/doPostWrite() which restore the user buffer if needed (e.g. in case data has been swapped out)

Only the transfer itself (step 2) will throw runtime exceptions and needs decoration. The pre and post steps only deal with buffers and should not throw. As the error handling decoration is a performance penalty, these functions should not be decorated.

**Task**
Remove the functions doPreRead(), doPreWrite(),  doPostRead() and doPostWrite() from the ExceptionHandlingDecorator if they only delegate. As it is derrived from NDRegisterAccessorDecorator, which already implements all delegations, the overloaded functions can simply be removed.
For those functions which in addition do something remove the genericTransfer "decoration" and directly call the delegated function.

**Comment by mhier** [comment]
Pull request created.
