### ISSUE TITLE
Coding Style: Variables in ExceptionHandlingDecorator don't follow coding style rules

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#92]
The variable names in the ExceptionHandlingDecorator don't follow the coding style rules.
* Class-wide variables should start with _
* Variable names are not descriptive (dm for instance is not good in class wide scope. Should be _deviceModule)

**Comment by mhier** [comment]
Close for now. This affects around 90% of the code in the framework.
