### ISSUE TITLE
Separate data invalid propagation from exception information propagation

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#99]
Currently the MetaDataPropagatingRegisterDecorator and the ErrorHandlingDecorator both use 
EntitiyOwner::incrementDataFaultCounter() and decrementDataFaultCounter with a flag whether to write the outputs again (set true by the exception handling).
For the normal invalidity flag propagation the loop runs through and writes the outputs, hence it is not necessary to write again.

However, using the same counter for both scenarios causes a scenario that does not always work. If a working push-input is supposed to transport the data invalid flag through the module, and the main loop is blocked by a poll-input which is reporting an exception while doing so, nothing is propagated. The exception sees that the module already is on invalid and does not re-write all outputs. This can be solved by having two counters, one for invalidData flags, one for exceptions.

Notice: It might be that a bool instead of a counter would be sufficient for the exceptions, because they are blocking. However, one has to consider carefully if there is not some situation where it might be that two accessors report an exception. Just use a counter. It makes the implementations more similar and it will just work.

Implementation:

* [x] Write a test that shows that the described scenario is failing at the moment.

Interface change:
* [x] Add pure virtual functions incrementExceptionCounter() and decrementExceptionCounter to the EntitiyOwner
* [x] Remove the bool flag from increment/decrementDataFaultCounter.
* [x] All functions that call increment/decrementDataFaultCounter(false) shall use increment/decrementDataFaultCounter() (should only be the MetaDataPropagatingRegisterAccessor)
* [x] All functions that call increment/decrementDataFaultCounter(true) shall use increment/decrementExceptionCounter()  (should only be the ExceptionHandlingDecorator)

Implementation:
* [x] Change the implementation (should only be ApplicationModule at the moment) to have a second counter variable exceptionCounter (and rename faultCounter to dataFaultCounter for more clarity)
* [x] Change increment/decremtDataFaultCounter to have as if "writeAllOutputs" was false
* [x] Implement increment/decrementExceptionCounter like increment/decremtDataFaultCounte(), except that it uses exceptionCounter.
* [ ] Change getDataValidity() to respect both counters.

* [ ] All tests, including the new one, should now pass.

**Comment by ckampm** [comment]
How both counters have to be taken into account is not really clear to me at the moment. A lot of tests are failing currently. A guess from the current test output is that the DataValidity is not properly set on startup.

**Comment by ckampm** [comment]
The changes described above lead to a conflict with the way `localValidity` is initialized in the `ExceptionHandlingDecorator` for read-only accessors. This leads to a raise of the assertion in `decrementExceptionCounter`.  Can the init has to be changed so the inital value matches the delategatedValiditidy from the underlying accessor? Otherwise the assertion has to be prevented on the first successful read.

**Comment by killenb** [comment]
The trick was to increase the exception count in the owner for every read accessor that is added. I also cleaned up the logic (is not a local data validity, but a flag whether there has been an exception).

Closed in 465cd69d094bae6f77115983b932ed37d6b147a3
